services:
  db:
    image: mysql:8.0
    container_name: app_db
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_backend
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8080"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: app_db
      DB_USERNAME: app_user
      DB_PASSWORD: app_pass
    depends_on:
      - db
  
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: node:20-alpine
    container_name: app_front
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: sh -c "npm install && npm start"

volumes:
  dbdata: